version: '3.8'
services:
  application:
    build: .
    image: jefersonfrancisco/notification
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://database:5432/notification
      - POSTGRES_USER=notification
      - POSTGRES_PASSWORD=notification
    depends_on:
      - database
  database:
    image: 'postgres'
    container_name: "notification-db"
    environment:
      POSTGRES_PASSWORD: "notification"
      POSTGRES_USER: "notification"
      POSTGRES_DB: "notification"
