version: '3.8'
services:
  postgres-compose:
    image: 'postgres'
    container_name: "notification-db"
    environment:
      POSTGRES_PASSWORD: "notification"
      POSTGRES_USER: "notification"
      POSTGRES_DB: "notification"
    ports:
      - 5433:5432
    expose:
      - 5433